platform :ios, '13.0'

flutter_sdk_path = File.expand_path('~/Library/Developer/flutter')
require File.join(flutter_sdk_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
